name: santa_barbara
description: Unindo a comunidade católica
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  animated_splash_screen: ^1.3.0
  grock: ^0.5.1
  # flutter_boom_menu_new: ^1.0.1
  firebase_core: ^3.0.0
  page_transition: ^2.1.0
  firebase_analytics: ^11.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  sticky_grouped_list: ^3.1.0
  flexible_grid_view: ^0.0.2
  simple_rich_text: ^2.0.49
  sliver_app_bar_builder: ^1.1.0
  shared_preferences: ^2.2.2
  drop_cap_text: ^1.1.3
  get_cli: ^1.8.1
  get: ^4.6.6
  z_grouped_list: ^1.0.8
  clickable_list_wheel_view: ^0.2.0
  material_text_fields: ^1.0.3
  material_dialogs: ^1.1.4
  google_maps_flutter: ^2.5.0
  flutter_carousel_slider: ^1.1.0
  custom_radio_grouped_button: ^2.2.1
  google_fonts: ^6.2.1
  emoji_alert: ^1.1.0
  circular_countdown_timer: ^0.2.3
  uuid: ^4.2.2
  google_sign_in: ^6.2.1
  googleapis: ^13.1.0
  googleapis_auth: ^1.4.1
  flutter_secure_storage: ^8.1.0
  pulsator: ^1.0.0+2
  cross_fade: ^0.4.0
  go_router: ^14.1.4
  avatar_glow: ^3.0.1
  animated_button_bar: ^1.0.0
  convex_bottom_bar: ^3.2.0
  floating_bottom_navigation_bar: ^1.5.2
  sz_fancy_bottom_navigation: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/paroco/
    - assets/icon/
    - assets/videos/
    - assets/gifs/